# Generated by Django 2.1.2 on 2019-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgtxt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
